name:                rules
version:             0.1.0.0
github:              "arthur-xavier/rules"
license:             BSD3
author:              "Arthur Xavier"
maintainer:          "arthur.xavierx@gmail.com"
copyright:           "2019 Arthur Xavier"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/arthur-xavier/rules#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- time
- transformers

default-extensions: NoImplicitPrelude

library:
  source-dirs: src

executables:
  rules-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rules
